events {}

http {
    server {
        listen 80;
        server_name orionstellar.com www.orionstellar.com;

        # Rule for Certbot challenge tokens
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Fallback to route everything else to your app
        location / {
            proxy_pass http://cloud_orionstellar_app:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}